include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    directives_ordering: error
    always_use_package_imports: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - "packages/**"

linter:
  rules:
    directives_ordering: true
    always_use_package_imports: true
    avoid_relative_lib_imports: false
    prefer_relative_imports: false
