# Generated code do not commit.
file(TO_CMAKE_PATH "/home/dreamier/flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/mnt/DevData/github/Sinan Note" PROJECT_DIR)

set(FLUTTER_VERSION "2.1.9+3275" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 2 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 9 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 3275 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/home/dreamier/flutter"
  "PROJECT_DIR=/mnt/DevData/github/Sinan Note"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzguNA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NjZkZDkzZjlhMg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049YTVjYjk2MzY5ZQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMC4z"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=/mnt/DevData/github/Sinan Note/.dart_tool/package_config.json"
  "FLUTTER_TARGET=/mnt/DevData/github/Sinan Note/lib/main.dart"
)
